export const GAME_REPOSITORY = 'GAME_REPOSITORY';
export const GAME_IMAGE_REPOSITORY = 'GAME_IMAGE_REPOSITORY';
export const GAME_INFORMATION_REPOSITORY = 'GAME_INFORMATION_REPOSITORY';
export const GAME_COMMENT_REPOSITORY = 'GAME_COMMENT_REPOSITORY';
export const GAME_COMMENT_SUB_REPOSITORY = 'GAME_COMMENT_SUB_REPOSITORY';
export const GAME_REACTION_REPOSITORY = 'GAME_REACTION_REPOSITORY';
